# Site
name: TechFirst Leaders
title: TechFirst Leaders 技術ブログ
description: "「エンジニアの成長と成功を科学する企業」 株式会社TechFirst Leadersの技術ブログです。"
logo: 'assets/images/tfl_logo_m.png'
favicon: 'assets/images/favicon.ico'
google_analytics: 'G-CNB937SR1X'
comments: false
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: [ "_pages" ]
permalink: /:title/
email: contact@techfirst-leaders.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techfrirst-leaders.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Authors
authors:
  nw:
    name: Naoki Wada
    display_name: Wada
    gravatar: 1bb38c77a1d988daf47530148dc0de69
    email: naoki.wada@techfirst-leaders.com
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page/:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock ]
